### ISSUE TITLE
add to reactos as pach for have a reasonable Mixer

### ISSUE THREAD

**Issue by blackcrack** [blargoner/mixerplus#1]
Hi,

why do you not add this Mixer to Reactos as pach or something.. or something.
it's perfect timeline for supporting Reactos.org an WinNT from the Community

best regards
Blacky

**Comment by ghost** [comment]
Hello. Blackcrack doesn't speak English properly, so please let me explain.

On behalf of ReactOS Project, which is an Open Source implementation of Windows NT-compatible operating system, he would like to ask for permission to include your sound mixer into ReactOS codebase (since its own implementation is rather buggy).

However, it is not clear if your code is actually GPL, BSD or MIT-compatible, since you did not put the license into the codebase. Would you please clear this up?

Also, is it possible for you to contribute to ReactOS Project in the future (i.e. redesign the application to resemble the stock Windows 2003's sound mixer, etc.)?

**Comment by blargoner** [comment]
@blackcrack @dsp2003 Thanks for your interest in my project. I only created this in the past to learn the Win32 Mixer API, so I didn't think of adding a license.

I'd be happy to add a license and have it included in ReactOS. Would this require GPL?

I'm not able to commit to supporting or maintaining the code, or redesigning the mixer to better match the default Windows sound mixer, at this time. But I will look more at the ReactOS project and consider contributing in the future.

**Comment by blackcrack** [comment]
Hi blagoner, bsp2003,

i guess GPL it's ever well :+1: 
but you should ask in the reactos chan @irc
or in the forum, there is a discussion about : 
https://www.reactos.org/forum/viewtopic.php?f=2&t=15601
i want you warmly invite :) 
happy coding ! 

http://wiki.reactos.org/developing
https://reactos.org/wiki/Welcome_to_the_ReactOS_Development_Wiki

**Comment by blargoner** [comment]
I licensed it under the GPL. Closing this issue.

**Comment by ghost** [comment]
Sadly, GPL v3 is not compatible with the codebase (as it restricts code embedding). Please consider downgrading it to GPL v2. Sorry for inconvenience, I should have clarified this earlier. :(

**Comment by blargoner** [comment]
@dsp2003 Done.

**Comment by ghost** [comment]
Thank you! Good luck with your projects. ^w^/)

**Comment by blackcrack** [comment]
:+1:  Thank you very much  ! :)

best regards and many and good luck with you Project whant i say too :)
Blacky
